name: spark
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  # Allows you to run this workflow manually from the Actions tab
  repository_dispatch:
    types: [spark]
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  spark:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest 
     permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write

    steps:
    - uses: actions/checkout@v4
    - run: ls -la 
        - run: spark-submit --version
    - run: spark-submit --master local hello.py
    - run: ls -la  
 - name: GIT commit and push docs
      env: 
        CI_COMMIT_MESSAGE: save spark results
        CI_COMMIT_AUTHOR: LuisAlexis10
      run: |
        git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
        git config --global user.email "211u0597@alumono.itssat.edu.mx"
        git add results
        git commit -m "${{ env.CI_COMMIT_MESSAGE }}"
        git push


